baseURL = 'https://e-mar404.dev/'
languageCode = 'en-us'
title = 'e-mar404 | Dev Logs'
enableEmoji = true

[pagination]
  disableAliases = false
  pagerSize = 20
  path = 'page'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
